### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by aitormagan** [okfn/ckan.js#19]
Hi,

I've tried to use this module but it's not working for me. CKAN is always returning 400 ValidationError. 

I've check the code and I think that I've found the error (at least the solution is working for me). In `ckan.js:144` I've replaced `request(conf,...` by `request.post(conf,...`.  By including `.post`, the request library is making a `POST` request so the parameters can be sent. Otherwise, the request library will make a `GET` request without parameters.

BR

**Comment by luiscape** [comment]
Hi @aitormagan is it worth making a pull request? At some point I got some odd requests errors as well. I haven't tried this solution yet, but this makes sense to me.

**Comment by aitormagan** [comment]
I've created the PR. You can check it now! :)

**Comment by aitormagan** [comment]
I've discovered where the bug was (#20). `npm` was installing a previous version (0.2.2). Now, the `npm` version has been updated and it works fine :)

**Comment by rgrp** [comment]
Great to know this was easily fixed and that was a version issue.

**Comment by luiscape** [comment]
That's great!
