### ISSUE TITLE
Increment version on npm

### ISSUE THREAD

**Issue by timwis** [okfn/ckan.js#20]
Just spent a long while debugging only to realize `npm install ckan` installs version `0.2.2` instead of the latest, `0.2.3` :P

**Comment by rgrp** [comment]
FIXED. Thanks for flagging and apologies for the hassle. BTW what are you using ckan.js for?

**Comment by timwis** [comment]
No problem! We've built a custom application to manage our metadata and I just wrote a node.js script to push changes directly to CKAN (opendataphilly.org). 

https://github.com/CityOfPhiladelphia/metadata-pusher
