### ISSUE TITLE
A widget based on ckan.js

### ISSUE THREAD

**Issue by loleg** [okfn/ckan.js#29]
Recently I worked on [ckan-embed](https://github.com/opendata-swiss/ckan-embed), supported by [opendata.swiss](https://opendata.swiss/en/about/). It is a small jQuery-based widget which uses CORS/JSONP to fetch data from CKAN using this library (see related issue #27). 

I would like to encourage some discussion/adoption of this approach, at least in the interest of promoting data reuse. Would this make sense as a feature request in CKAN itself (akin to [data viewer](http://docs.ckan.org/en/latest/maintaining/data-viewer.html)), or something for OKFN labs, or just write about it in a wiki somewhere? 

It's tightly coupled to `ckan.js`, which is why I'm asking here. I also figure other users of this library have built similar things.

**Comment by rufuspollock** [comment]
@loleg great work! I definitely think this is something to write up as a post for OK Labs blog and to also mention on the ckan channels. It would be nice to have a systematic list of CKAN widgets like the list of extensions.

PS: have you seen https://github.com/rufuspollock/ckan-explorer (this is quite different - more a data explorer but also builds on ckan.js).

**Comment by loleg** [comment]
Thanks @rufuspollock - that's a nice suggestion, let's do a post as soon as the widget is live in a production site. I have not come across Data Explorer before, but will give it a try, and put some more thought into the idea.

Open to the idea of collaborating on a list of widgets - the wiki is not enabled in this repo; where do you think this should live?

**Comment by rufuspollock** [comment]
@loleg i think we could maybe add the widgets to http://extensions.ckan.org/ - https://github.com/ckan/extensions.ckan.org
